Update patch set 1
Patch Set 1:

I can build this in tree but when trying standalone build I get errors

$ git clone https://gerrit.googlesource.com/plugins/uploadvalidator
Cloning into 'uploadvalidator'...
remote: Total 422 (delta 60), reused 422 (delta 60)
Receiving objects: 100% (422/422), 104.14 KiB | 0 bytes/s, done.
Resolving deltas: 100% (60/60), done.
Checking connectivity... done.
[d029788@WDFM32389938A git]$ cd uploadvalidator/
[d029788@WDFM32389938A uploadvalidator (master)]$ buck build uploadvalidator
Not using buckd because watchman isn't installed.
Parse error for build file /Users/d029788/tmp/git/uploadvalidator/BUCK:   File "/Users/d029788/tmp/git/uploadvalidator/BUCK", line 1, in <module>
    include_defs('//bucklets/gerrit_plugin.bucklet')
  File "/Users/d029788/tmp/git/uploadvalidator/buck-out/tmp/buck_run.qLB3QJ/buck6150541681241774248.py", line 521, in _include_defs
    implicit_includes=implicit_includes)
  File "/Users/d029788/tmp/git/uploadvalidator/buck-out/tmp/buck_run.qLB3QJ/buck6150541681241774248.py", line 622, in _process_include
    implicit_includes=implicit_includes)
  File "/Users/d029788/tmp/git/uploadvalidator/buck-out/tmp/buck_run.qLB3QJ/buck6150541681241774248.py", line 597, in _process
    with open(path) as f:
IOError: [Errno 2] No such file or directory: '/Users/d029788/tmp/git/uploadvalidator/bucklets/gerrit_plugin.bucklet'

[-] PARSING BUCK FILES...FINISHED 0.1s

Patch-set: 1