Update patch set 1
Patch Set 1: Verified-1

1) skipWhenUserBelongsToGroupName(com.googlesource.gerrit.plugins.uploadvalidator.SkipValidationTest)
java.lang.IllegalStateException: Missing required properties: members subgroups

Patch-set: 1
Reviewer: Gerrit User 1010008 <1010008@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1