Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> As of this change, it seems the uploadvalidator plugin no longer builds standalone:
> 
> ERROR: ~/.cache/bazel/_bazel_bbadour/d42a232fad7dc0b3e7b9d68cd82f4f83/external/com_googlesource_gerrit_bazlets/gerrit_api_maven_local.bzl:27:5: no such package '@gerrit_acceptance_framework//jar': failed /usr/bin/python ~/.cache/bazel/_bazel_bbadour/d42a232fad7dc0b3e7b9d68cd82f4f83/external/com_googlesource_gerrit_bazlets/tools/download_file.py -o ~/.cache/bazel/_bazel_bbadour/d42a232fad7dc0b3e7b9d68cd82f4f83/external/gerrit_acceptance_framework/jar/gerrit-acceptance-framework-3.0.0-SNAPSHOT.jar -u MAVEN_LOCAL:/com/google/gerrit/gerrit-acceptance-framework/3.0.0-SNAPSHOT/gerrit-acceptance-framework-3.0.0-SNAPSHOT.jar: Download file://~/.m2/repository/com/google/gerrit/gerrit-acceptance-framework/3.0.0-SNAPSHOT/gerrit-acceptance-framework-3.0.0-SNAPSHOT.jar
> error using curl: Command '['curl', '--proxy-anyauth', '-ksfo', '~/.gerritcodereview/bazel-cache/downloaded-artifacts/gerrit-acceptance-framework-3.0.0-SNAPSHOT.jar-e2b3691d0cc1931fdcc6255b71b6c7b1f63f2332', 'file://~/.m2/repository/com/google/gerrit/gerrit-acceptance-framework/3.0.0-SNAPSHOT/gerrit-acceptance-framework-3.0.0-SNAPSHOT.jar']' returned non-zero exit status 37
>  and referenced by '//external:gerrit-acceptance-framework'
> ERROR: Analysis of target '//:testutils' failed; build aborted: Analysis failed
> INFO: Elapsed time: 0.219s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
>     Fetching @bouncycastle_bcpkix; fetching
>     Fetching @bouncycastle_bcprov; fetching
>     Fetching @gerrit_plugin_api; fetching
>     Fetching @gerrit_acceptance_framework; fetching
> 
> Path to my home directory redacted by replacing with ~

You need to build and deploy the snapshot API from the gerrit project at the head of master.

 $ bazel build api
 $ ./tools/maven/api.sh api_deploy

Patch-set: 2